[[footer]]
name = "HOME"
url = ""
weight = "1"
[[footer]]
name = "PRODOTTI"
url = "project/"
weight = 3
[[footer]]
name = "HIDDEN"
url = "service/"
weight = 4
[[footer]]
name = "HIDDEN2"
url = "pricing/"
weight = 5
[[footer]]
name = "FABBRICA 4.0"
url = "faq/"
weight = 6
[[footer]]
name = "CONTATTI"
url = "contact/"
weight = 7
[[main]]
name = "HOME"
url = ""
weight = 1
[[main]]
name = "PRODOTTI"
url = "project/"
weight = 3
[[main]]
name = "HIDDEN4"
parent = "More"
url = "service/"
weight = 1
[[main]]
name = "HIDDEN3"
parent = "More"
url = "pricing/"
weight = 2
[[main]]
name = "FABBRICA 4.0"
parent = "More"
url = "faq/"
weight = "6"
[[main]]
name = "CONTATTI"
url = "contact/"
weight = 6
