[[footer]]
name = "DOWNLOAD"
url = ""
weight = "8"
[[footer]]
name = "TELEFONO 0742 381401"
url = "contact/"
weight = "9"
[[footer]]
name = "HOME"
url = ""
weight = "1"
[[footer]]
name = "PRODOTTI"
url = "project/"
weight = 3
[[footer]]
name = "FABBRICA 4.0"
url = "faq/"
weight = 6
[[footer]]
name = "CONTATTI"
url = "contact/"
weight = 7
[[main]]
name = "HOME"
url = ""
weight = 1
[[main]]
name = "PRODOTTI"
url = "project/"
weight = 3
[[main]]
name = "FABBRICA 4.0"
url = "faq/"
weight = "6"
[[main]]
name = "CONTATTI"
url = "contact/"
weight = "7"
