[[footer]]
name = "HOME"
url = ""
weight = "1"
[[footer]]
name = "PRODOTTI"
url = "project/"
weight = 3
[[footer]]
name = "FABBRICA 4.0"
url = "faq/"
weight = 6
[[footer]]
name = "CONTATTI"
url = "contact/"
weight = 7
[[main]]
name = "HOME"
url = ""
weight = 1
[[main]]
name = "PRODOTTI"
url = "project/"
weight = 3
[[main]]
name = "FABBRICA 4.0"
url = "faq/"
weight = "6"
[[main]]
name = "CONTATTI"
url = "contact/"
weight = "7"
